// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// mirror_desc
arma::mat mirror_desc(arma::mat X0_scaled, arma::mat X1_scaled, arma::mat V, int niter, double rel_tol);
RcppExport SEXP _MirrorDescSynth_mirror_desc(SEXP X0_scaledSEXP, SEXP X1_scaledSEXP, SEXP VSEXP, SEXP niterSEXP, SEXP rel_tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X0_scaled(X0_scaledSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1_scaled(X1_scaledSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type V(VSEXP);
    Rcpp::traits::input_parameter< int >::type niter(niterSEXP);
    Rcpp::traits::input_parameter< double >::type rel_tol(rel_tolSEXP);
    rcpp_result_gen = Rcpp::wrap(mirror_desc(X0_scaled, X1_scaled, V, niter, rel_tol));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MirrorDescSynth_mirror_desc", (DL_FUNC) &_MirrorDescSynth_mirror_desc, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_MirrorDescSynth(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
