# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Mirror Descent (Exponentiated Gradient Descent) for Synthetic Control.
#'
#' This algorithm is from Aethy et al. (2017; Matrix Completion). This
#' function will minimize with respect to w
#'
#' (X0 * w - X1)'(X0 * w - X1)
#'
#' The matrix X where X0 is the controls and X1 is the treated vector.
#' Before passing X1 and X0 to this function, X needs to be scaled
#' to have zero rowmeans, variance 1, and normalized by the largest value.
#'
#' @title Mirror Descent (Exponentiated Gradient Descent) for Synthetic Control
#' @param X0_scaled The scaled matrix of controls
#' @param X1_scaled The scaled matrix (column vector) for the treated values
#' @param V The diagonal matrix for the weights for each variable
#' @param niter The number of interations for the algorithm. Defauls to
#' 10,000
#' @param rel_tol The stopping tolerance. Defaults to 1e-8
#' @export
mirror_desc <- function(X0_scaled, X1_scaled, V, niter = 10000L, rel_tol = 1e-8) {
    .Call('_MirrorDescSynth_mirror_desc', PACKAGE = 'MirrorDescSynth', X0_scaled, X1_scaled, V, niter, rel_tol)
}

